# Generated by Django 5.2.10 on 2026-02-02 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("university", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Matricule"
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("ASSISTANT", "Assistant"),
                            ("LECTURER", "Maître assistant"),
                            ("SENIOR_LECTURER", "Maître de conférences"),
                            ("ASSOCIATE_PROFESSOR", "Professeur associé"),
                            ("PROFESSOR", "Professeur"),
                        ],
                        default="ASSISTANT",
                        max_length=30,
                        verbose_name="Grade",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("CONTRACT", "Contractuel"),
                            ("VISITING", "Vacataire"),
                            ("PART_TIME", "Temps partiel"),
                        ],
                        default="PERMANENT",
                        max_length=20,
                        verbose_name="Type de contrat",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="Date d'embauche")),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Spécialisation"
                    ),
                ),
                (
                    "office_location",
                    models.CharField(blank=True, max_length=100, verbose_name="Bureau"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teachers",
                        to="university.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "TEACHER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enseignant",
                "verbose_name_plural": "Enseignants",
                "ordering": ["employee_id"],
            },
        ),
        migrations.CreateModel(
            name="TeacherContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de contrat"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Salaire de base"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Actif"),
                            ("EXPIRED", "Expiré"),
                            ("TERMINATED", "Résilié"),
                            ("RENEWED", "Renouvelé"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contracts/",
                        verbose_name="Document",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="teachers.teacher",
                        verbose_name="Enseignant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrat",
                "verbose_name_plural": "Contrats",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TeacherCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True, verbose_name="Enseignant principal"
                    ),
                ),
                ("assigned_date", models.DateField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_assignments",
                        to="academics.course",
                        verbose_name="Cours",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_assignments",
                        to="university.semester",
                        verbose_name="Semestre",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_assignments",
                        to="teachers.teacher",
                        verbose_name="Enseignant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affectation cours",
                "verbose_name_plural": "Affectations cours",
                "unique_together": {("teacher", "course", "semester")},
            },
        ),
    ]
