# Generated by Django 5.2.10 on 2026-02-02 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Nom"),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Année en cours"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Année académique",
                "verbose_name_plural": "Années académiques",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Bâtiment"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(default=30, verbose_name="Capacité"),
                ),
                (
                    "has_projector",
                    models.BooleanField(default=False, verbose_name="Projecteur"),
                ),
                (
                    "has_computers",
                    models.BooleanField(default=False, verbose_name="Ordinateurs"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
            ],
            options={
                "verbose_name": "Salle de classe",
                "verbose_name_plural": "Salles de classe",
                "ordering": ["building", "name"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("L1", "Licence 1"),
                            ("L2", "Licence 2"),
                            ("L3", "Licence 3"),
                            ("M1", "Master 1"),
                            ("M2", "Master 2"),
                            ("D1", "Doctorat 1"),
                            ("D2", "Doctorat 2"),
                            ("D3", "Doctorat 3"),
                        ],
                        max_length=2,
                        unique=True,
                        verbose_name="Niveau",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Ordre")),
            ],
            options={
                "verbose_name": "Niveau",
                "verbose_name_plural": "Niveaux",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dean",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "DEAN"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faculty_dean",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Doyen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculté",
                "verbose_name_plural": "Facultés",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["TEACHER", "DEAN"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_head",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Chef de département",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="university.faculty",
                        verbose_name="Faculté",
                    ),
                ),
            ],
            options={
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
                "ordering": ["faculty", "name"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "duration_years",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Durée (années)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "tuition_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Frais de scolarité",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="university.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programs",
                        to="university.level",
                        verbose_name="Niveau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme",
                "verbose_name_plural": "Programmes",
                "ordering": ["department", "level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester_type",
                    models.CharField(
                        choices=[("S1", "Semestre 1"), ("S2", "Semestre 2")],
                        max_length=2,
                        verbose_name="Type de semestre",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, verbose_name="Semestre en cours"
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="university.academicyear",
                        verbose_name="Année académique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Semestre",
                "verbose_name_plural": "Semestres",
                "ordering": ["academic_year", "semester_type"],
                "unique_together": {("academic_year", "semester_type")},
            },
        ),
    ]
