# Generated by Django 4.2.7 on 2026-02-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="program",
            options={
                "ordering": ["department", "name"],
                "verbose_name": "Programme",
                "verbose_name_plural": "Programmes",
            },
        ),
        migrations.RemoveField(
            model_name="program",
            name="level",
        ),
        migrations.AddField(
            model_name="program",
            name="levels",
            field=models.ManyToManyField(
                related_name="programs", to="university.level", verbose_name="Niveaux"
            ),
        ),
    ]
