# Generated by Django 5.2.10 on 2026-02-02 11:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("university", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SALARIES", "Salaires"),
                            ("UTILITIES", "Services publics"),
                            ("MAINTENANCE", "Maintenance"),
                            ("EQUIPMENT", "Équipement"),
                            ("SUPPLIES", "Fournitures"),
                            ("OTHER", "Autres"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="expenses/",
                        verbose_name="Reçu",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approuvé par",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dépense",
                "verbose_name_plural": "Dépenses",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TuitionPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Espèces"),
                            ("BANK_TRANSFER", "Virement bancaire"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CHECK", "Chèque"),
                        ],
                        default="CASH",
                        max_length=20,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("COMPLETED", "Complété"),
                            ("FAILED", "Échoué"),
                            ("REFUNDED", "Remboursé"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro de reçu"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Date de paiement")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tuition_payments",
                        to="university.academicyear",
                        verbose_name="Année académique",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reçu par",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tuition_payments",
                        to="students.student",
                        verbose_name="Étudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement de scolarité",
                "verbose_name_plural": "Paiements de scolarité",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveIntegerField(verbose_name="Mois")),
                ("year", models.PositiveIntegerField(verbose_name="Année")),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Salaire de base"
                    ),
                ),
                (
                    "bonuses",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Primes",
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Déductions",
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Salaire net"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PAID", "Payé"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Remarques")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salaries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_salaries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Traité par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salaire",
                "verbose_name_plural": "Salaires",
                "ordering": ["-year", "-month"],
                "unique_together": {("employee", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="StudentBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total dû",
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total payé",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_balances",
                        to="university.academicyear",
                        verbose_name="Année académique",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="students.student",
                        verbose_name="Étudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solde étudiant",
                "verbose_name_plural": "Soldes étudiants",
                "unique_together": {("student", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="TuitionFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "installments_allowed",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre de tranches"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Date limite")),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tuition_fees",
                        to="university.academicyear",
                        verbose_name="Année académique",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tuition_fees",
                        to="university.program",
                        verbose_name="Programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frais de scolarité",
                "verbose_name_plural": "Frais de scolarité",
                "unique_together": {("program", "academic_year")},
            },
        ),
    ]
