# Generated by Django 5.2.10 on 2026-02-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Homme"), ("F", "Femme")],
                default="M",
                max_length=1,
                verbose_name="Sexe",
            ),
        ),
    ]
