# Generated by Django 5.2.10 on 2026-02-02 11:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Note finale",
                    ),
                ),
                (
                    "grade_letter",
                    models.CharField(blank=True, max_length=2, verbose_name="Mention"),
                ),
                (
                    "is_validated",
                    models.BooleanField(default=False, verbose_name="Validé"),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Note de cours",
                "verbose_name_plural": "Notes de cours",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("MIDTERM", "Partiel"),
                            ("FINAL", "Final"),
                            ("QUIZ", "Quiz"),
                            ("PRACTICAL", "TP noté"),
                            ("PROJECT", "Projet"),
                            ("ORAL", "Oral"),
                            ("RESIT", "Rattrapage"),
                        ],
                        max_length=20,
                        verbose_name="Type d'examen",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=5,
                        verbose_name="Note maximale",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Poids",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Examen",
                "verbose_name_plural": "Examens",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Note",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Remarques")),
                (
                    "is_absent",
                    models.BooleanField(default=False, verbose_name="Absent"),
                ),
                ("graded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "ordering": ["exam", "student"],
            },
        ),
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=4,
                        verbose_name="Moyenne générale",
                    ),
                ),
                (
                    "total_credits",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Crédits totaux"
                    ),
                ),
                (
                    "credits_earned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Crédits obtenus"
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Rang"
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Observations")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publié"),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Bulletin de notes",
                "verbose_name_plural": "Bulletins de notes",
                "ordering": ["-semester", "student"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("REQUIRED", "Obligatoire"),
                            ("ELECTIVE", "Optionnel"),
                            ("PRACTICAL", "Travaux pratiques"),
                        ],
                        default="REQUIRED",
                        max_length=20,
                        verbose_name="Type de cours",
                    ),
                ),
                (
                    "credits",
                    models.PositiveIntegerField(default=3, verbose_name="Crédits"),
                ),
                (
                    "hours_lecture",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Heures de cours"
                    ),
                ),
                (
                    "hours_practical",
                    models.PositiveIntegerField(default=0, verbose_name="Heures TP"),
                ),
                (
                    "hours_tutorial",
                    models.PositiveIntegerField(default=0, verbose_name="Heures TD"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("1.0"),
                        max_digits=3,
                        verbose_name="Coefficient",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="required_for",
                        to="academics.course",
                        verbose_name="Prérequis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cours",
                "verbose_name_plural": "Cours",
                "ordering": ["program", "code"],
            },
        ),
    ]
