# Generated by Django 5.2.10 on 2026-02-02 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("students", "0001_initial"),
        ("university", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="university.program",
                verbose_name="Programme",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="university.semester",
                verbose_name="Semestre",
            ),
        ),
        migrations.AddField(
            model_name="coursegrade",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_grades",
                to="academics.course",
                verbose_name="Cours",
            ),
        ),
        migrations.AddField(
            model_name="coursegrade",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_grades",
                to="university.semester",
                verbose_name="Semestre",
            ),
        ),
        migrations.AddField(
            model_name="coursegrade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_grades",
                to="students.student",
                verbose_name="Étudiant",
            ),
        ),
        migrations.AddField(
            model_name="coursegrade",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_grades",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validé par",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams",
                to="university.classroom",
                verbose_name="Salle",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="academics.course",
                verbose_name="Cours",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="university.semester",
                verbose_name="Semestre",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="academics.exam",
                verbose_name="Examen",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="graded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_exams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Noté par",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="students.student",
                verbose_name="Étudiant",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_report_cards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Généré par",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_cards",
                to="university.semester",
                verbose_name="Semestre",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_cards",
                to="students.student",
                verbose_name="Étudiant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coursegrade",
            unique_together={("student", "course", "semester")},
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("student", "exam")},
        ),
        migrations.AlterUniqueTogether(
            name="reportcard",
            unique_together={("student", "semester")},
        ),
    ]
