# Generated by Django 4.2.7 on 2026-02-03 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0002_alter_program_options_remove_program_level_and_more"),
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["program", "level", "semester_type", "code"],
                "verbose_name": "Cours",
                "verbose_name_plural": "Cours",
            },
        ),
        migrations.RemoveField(
            model_name="course",
            name="semester",
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="university.level",
                verbose_name="Niveau",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="semester_type",
            field=models.CharField(
                choices=[("S1", "Semestre 1"), ("S2", "Semestre 2")],
                default="S1",
                max_length=2,
                verbose_name="Semestre",
            ),
        ),
    ]
