# Generated by Django 4.2.7 on 2026-02-03 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0002_alter_program_options_remove_program_level_and_more"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annual_gpa",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Moyenne annuelle"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("PROMOTED", "Admis(e)"),
                            ("REPEATED", "Redoublant(e)"),
                            ("FAILED", "Exclu(e)/Echec"),
                            ("CONDITIONAL", "Admis(e) avec dettes"),
                        ],
                        max_length=20,
                        verbose_name="Décision",
                    ),
                ),
                (
                    "decision_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date de décision"
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Remarques")),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="university.academicyear",
                        verbose_name="Année académique",
                    ),
                ),
                (
                    "level_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions_from",
                        to="university.level",
                        verbose_name="Niveau précédent",
                    ),
                ),
                (
                    "level_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions_to",
                        to="university.level",
                        verbose_name="Niveau suivant",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="university.program",
                        verbose_name="Programme",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="students.student",
                        verbose_name="Étudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Délibération",
                "verbose_name_plural": "Délibérations",
                "ordering": ["-academic_year", "student"],
                "unique_together": {("student", "academic_year")},
            },
        ),
    ]
