# Generated by Django 4.2.7 on 2026-02-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_studentpromotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="students/photos/",
                verbose_name="Photo de profil",
            ),
        ),
    ]
