# Generated by Django 5.2.10 on 2026-02-02 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("teachers", "0001_initial"),
        ("university", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "Général"),
                            ("ACADEMIC", "Académique"),
                            ("FINANCIAL", "Financier"),
                            ("EXAM", "Examens"),
                            ("EVENT", "Événement"),
                        ],
                        default="GENERAL",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("ALL", "Tous"),
                            ("STUDENTS", "Étudiants"),
                            ("TEACHERS", "Enseignants"),
                            ("STAFF", "Personnel"),
                        ],
                        default="ALL",
                        max_length=20,
                        verbose_name="Public cible",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publié"),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Épinglé"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to="university.faculty",
                        verbose_name="Faculté",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to="university.program",
                        verbose_name="Programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annonce",
                "verbose_name_plural": "Annonces",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ],
                        verbose_name="Jour",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
            ],
            options={
                "verbose_name": "Créneau horaire",
                "verbose_name_plural": "Créneaux horaires",
                "ordering": ["day", "start_time"],
                "unique_together": {("day", "start_time", "end_time")},
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedules",
                        to="university.classroom",
                        verbose_name="Salle",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="academics.course",
                        verbose_name="Cours",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="university.semester",
                        verbose_name="Semestre",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="teachers.teacher",
                        verbose_name="Enseignant",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="scheduling.timeslot",
                        verbose_name="Créneau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emploi du temps",
                "verbose_name_plural": "Emplois du temps",
                "ordering": ["semester", "time_slot"],
            },
        ),
        migrations.CreateModel(
            name="CourseSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("LECTURE", "Cours magistral"),
                            ("TUTORIAL", "TD"),
                            ("PRACTICAL", "TP"),
                            ("EXAM", "Examen"),
                        ],
                        default="LECTURE",
                        max_length=20,
                        verbose_name="Type de séance",
                    ),
                ),
                (
                    "topic",
                    models.CharField(blank=True, max_length=200, verbose_name="Sujet"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="Annulé"),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="Raison d'annulation"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="scheduling.schedule",
                        verbose_name="Emploi du temps",
                    ),
                ),
            ],
            options={
                "verbose_name": "Séance de cours",
                "verbose_name_plural": "Séances de cours",
                "ordering": ["-date"],
                "unique_together": {("schedule", "date")},
            },
        ),
    ]
